version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:6
    networks:
      - backend

  nestjs:
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend
    ports:
      - "3000:3000"

  nextjs:
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    environment:
      API_URL: http://nestjs:3000
    depends_on:
      - nestjs
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
